/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CvContactItem {
        "icon": string;
    }
    interface CvHeader {
        /**
          * @default '#2c5f6f'
         */
        "color": string;
        "jobRole": string;
        "name": string;
    }
    interface CvList {
    }
    interface CvListItem {
        /**
          * @default '#2c5f6f'
         */
        "bulletColor": string;
    }
    interface CvMain {
    }
    interface CvProfileImage {
        /**
          * @default 'Profile Image'
         */
        "alt": string;
        /**
          * @default 'https://via.placeholder.com/200x200/4A90A4/FFFFFF?text=AG'
         */
        "src": string;
    }
    interface CvSection {
        /**
          * @default "#2c5f6f"
         */
        "color": string;
        "sectionTitle": string;
    }
    interface CvSectionItem {
        "heading": string;
        /**
          * @default '#2c5f6f'
         */
        "headingColor": string;
        "period": string;
        "subheading": string;
    }
    interface CvSidebar {
        /**
          * @default 'rgb(218, 228, 235)'
         */
        "backgroundColor": string;
    }
    interface CvSkillsList {
        /**
          * @default '#2c5f6f'
         */
        "bulletColor": string;
        /**
          * @default []
         */
        "skills": string[];
    }
}
declare global {
    interface HTMLCvContactItemElement extends Components.CvContactItem, HTMLStencilElement {
    }
    var HTMLCvContactItemElement: {
        prototype: HTMLCvContactItemElement;
        new (): HTMLCvContactItemElement;
    };
    interface HTMLCvHeaderElement extends Components.CvHeader, HTMLStencilElement {
    }
    var HTMLCvHeaderElement: {
        prototype: HTMLCvHeaderElement;
        new (): HTMLCvHeaderElement;
    };
    interface HTMLCvListElement extends Components.CvList, HTMLStencilElement {
    }
    var HTMLCvListElement: {
        prototype: HTMLCvListElement;
        new (): HTMLCvListElement;
    };
    interface HTMLCvListItemElement extends Components.CvListItem, HTMLStencilElement {
    }
    var HTMLCvListItemElement: {
        prototype: HTMLCvListItemElement;
        new (): HTMLCvListItemElement;
    };
    interface HTMLCvMainElement extends Components.CvMain, HTMLStencilElement {
    }
    var HTMLCvMainElement: {
        prototype: HTMLCvMainElement;
        new (): HTMLCvMainElement;
    };
    interface HTMLCvProfileImageElement extends Components.CvProfileImage, HTMLStencilElement {
    }
    var HTMLCvProfileImageElement: {
        prototype: HTMLCvProfileImageElement;
        new (): HTMLCvProfileImageElement;
    };
    interface HTMLCvSectionElement extends Components.CvSection, HTMLStencilElement {
    }
    var HTMLCvSectionElement: {
        prototype: HTMLCvSectionElement;
        new (): HTMLCvSectionElement;
    };
    interface HTMLCvSectionItemElement extends Components.CvSectionItem, HTMLStencilElement {
    }
    var HTMLCvSectionItemElement: {
        prototype: HTMLCvSectionItemElement;
        new (): HTMLCvSectionItemElement;
    };
    interface HTMLCvSidebarElement extends Components.CvSidebar, HTMLStencilElement {
    }
    var HTMLCvSidebarElement: {
        prototype: HTMLCvSidebarElement;
        new (): HTMLCvSidebarElement;
    };
    interface HTMLCvSkillsListElement extends Components.CvSkillsList, HTMLStencilElement {
    }
    var HTMLCvSkillsListElement: {
        prototype: HTMLCvSkillsListElement;
        new (): HTMLCvSkillsListElement;
    };
    interface HTMLElementTagNameMap {
        "cv-contact-item": HTMLCvContactItemElement;
        "cv-header": HTMLCvHeaderElement;
        "cv-list": HTMLCvListElement;
        "cv-list-item": HTMLCvListItemElement;
        "cv-main": HTMLCvMainElement;
        "cv-profile-image": HTMLCvProfileImageElement;
        "cv-section": HTMLCvSectionElement;
        "cv-section-item": HTMLCvSectionItemElement;
        "cv-sidebar": HTMLCvSidebarElement;
        "cv-skills-list": HTMLCvSkillsListElement;
    }
}
declare namespace LocalJSX {
    interface CvContactItem {
        "icon"?: string;
    }
    interface CvHeader {
        /**
          * @default '#2c5f6f'
         */
        "color"?: string;
        "jobRole"?: string;
        "name"?: string;
    }
    interface CvList {
    }
    interface CvListItem {
        /**
          * @default '#2c5f6f'
         */
        "bulletColor"?: string;
    }
    interface CvMain {
    }
    interface CvProfileImage {
        /**
          * @default 'Profile Image'
         */
        "alt"?: string;
        /**
          * @default 'https://via.placeholder.com/200x200/4A90A4/FFFFFF?text=AG'
         */
        "src"?: string;
    }
    interface CvSection {
        /**
          * @default "#2c5f6f"
         */
        "color"?: string;
        "sectionTitle"?: string;
    }
    interface CvSectionItem {
        "heading"?: string;
        /**
          * @default '#2c5f6f'
         */
        "headingColor"?: string;
        "period"?: string;
        "subheading"?: string;
    }
    interface CvSidebar {
        /**
          * @default 'rgb(218, 228, 235)'
         */
        "backgroundColor"?: string;
    }
    interface CvSkillsList {
        /**
          * @default '#2c5f6f'
         */
        "bulletColor"?: string;
        /**
          * @default []
         */
        "skills"?: string[];
    }
    interface IntrinsicElements {
        "cv-contact-item": CvContactItem;
        "cv-header": CvHeader;
        "cv-list": CvList;
        "cv-list-item": CvListItem;
        "cv-main": CvMain;
        "cv-profile-image": CvProfileImage;
        "cv-section": CvSection;
        "cv-section-item": CvSectionItem;
        "cv-sidebar": CvSidebar;
        "cv-skills-list": CvSkillsList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv-contact-item": LocalJSX.CvContactItem & JSXBase.HTMLAttributes<HTMLCvContactItemElement>;
            "cv-header": LocalJSX.CvHeader & JSXBase.HTMLAttributes<HTMLCvHeaderElement>;
            "cv-list": LocalJSX.CvList & JSXBase.HTMLAttributes<HTMLCvListElement>;
            "cv-list-item": LocalJSX.CvListItem & JSXBase.HTMLAttributes<HTMLCvListItemElement>;
            "cv-main": LocalJSX.CvMain & JSXBase.HTMLAttributes<HTMLCvMainElement>;
            "cv-profile-image": LocalJSX.CvProfileImage & JSXBase.HTMLAttributes<HTMLCvProfileImageElement>;
            "cv-section": LocalJSX.CvSection & JSXBase.HTMLAttributes<HTMLCvSectionElement>;
            "cv-section-item": LocalJSX.CvSectionItem & JSXBase.HTMLAttributes<HTMLCvSectionItemElement>;
            "cv-sidebar": LocalJSX.CvSidebar & JSXBase.HTMLAttributes<HTMLCvSidebarElement>;
            "cv-skills-list": LocalJSX.CvSkillsList & JSXBase.HTMLAttributes<HTMLCvSkillsListElement>;
        }
    }
}
